<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    public function run()
    {
        $foods = [
            [
                'nama' => 'Bubur Daging Tomat',
                'bahan' => 'Bubur daging tomat dibuat dengan daging sapi atau ayam, tomat, bawang putih, bawang merah, jahe (opsional), bumbu penyedap, dan air.',
                'cara' => 'Campur daging tomat dengan beras dan air, masak hingga mendidih.',
                'energi' => 247,
                'protein' => 15,
                'lemak' => 10,
                'karbo' => 25,
            ],
            [
                'nama' => 'Nasi Goreng',
                'bahan' => 'Nasi goreng adalah nasi yang digoreng dalam minyak dengan bawang putih, bawang merah, ayam atau udang, telur, dan kecap.',
                'cara' => 'Tumis bawang putih, bawang merah, dan daging/udang hingga harum, tambahkan nasi dan kecap, aduk hingga merata.',
                'energi' => 320,
                'protein' => 12,
                'lemak' => 14,
                'karbo' => 40,
            ],
            [
                'nama' => 'Capcay',
                'bahan' => 'Capcay adalah tumisan sayuran seperti wortel, kembang kol, sawi, jamur, udang/ayam, dengan bumbu kecap atau saus tiram.',
                'cara' => 'Tumis bawang putih, tambahkan sayuran dan daging/udang, masak hingga sayuran matang, tambahkan saus.',
                'energi' => 180,
                'protein' => 8,
                'lemak' => 5,
                'karbo' => 25,
            ],
            [
                'nama' => 'Soto Ayam',
                'bahan' => 'Soto ayam adalah sup ayam dengan kuah bening berbumbu kunyit, jahe, bawang putih, dan bawang merah.',
                'cara' => 'Rebus ayam dengan bumbu hingga matang, sajikan dengan tambahan mie, tauge, dan daun bawang.',
                'energi' => 280,
                'protein' => 18,
                'lemak' => 12,
                'karbo' => 30,
            ],
            [
                'nama' => 'Gado-Gado',
                'bahan' => 'Gado-gado adalah campuran sayuran rebus seperti kacang panjang, tahu, tempe, selada, bayam, dicampur dengan saus kacang.',
                'cara' => 'Rebus sayuran dan telur, sajikan dengan saus kacang.',
                'energi' => 210,
                'protein' => 10,
                'lemak' => 8,
                'karbo' => 28,
            ],
            [
                'nama' => 'Mie Goreng',
                'bahan' => 'Mie goreng adalah mie yang digoreng dengan minyak sayur, kemudian dicampur dengan bawang putih, bawang merah, telur, sayuran, dan kecap.',
                'cara' => 'Tumis bawang putih, bawang merah, dan telur, tambahkan mie dan sayuran, aduk hingga merata.',
                'energi' => 290,
                'protein' => 11,
                'lemak' => 15,
                'karbo' => 35,
            ],
            [
                'nama' => 'Ayam Bakar',
                'bahan' => 'Ayam bakar adalah potongan ayam yang dibakar dengan bumbu rempah, seperti bawang putih, bawang merah, kunyit, dan ketumbar.',
                'cara' => 'Bakar ayam hingga matang dan kecoklatan, sajikan dengan nasi dan sambal.',
                'energi' => 260,
                'protein' => 20,
                'lemak' => 12,
                'karbo' => 20,
            ],
            [
                'nama' => 'Bakso',
                'bahan' => 'Bakso adalah bola daging yang terbuat dari campuran daging sapi giling dan tepung tapioka, dimasak dalam kuah kaldu sapi.',
                'cara' => 'Rebus bakso dalam kuah kaldu hingga matang, tambahkan mie atau nasi jika diinginkan.',
                'energi' => 180,
                'protein' => 15,
                'lemak' => 8,
                'karbo' => 10,
            ],
            [
                'nama' => 'Pecel Lele',
                'bahan' => 'Pecel lele adalah ikan lele goreng tepung disajikan dengan sambal terasi dan sayuran pecel.',
                'cara' => 'Goreng ikan lele dengan tepung hingga kecoklatan, sajikan dengan sambal terasi dan lalapan.',
                'energi' => 320,
                'protein' => 25,
                'lemak' => 18,
                'karbo' => 15,
            ],
            [
                'nama' => 'Rendang',
                'bahan' => 'Rendang adalah daging sapi yang dimasak dalam santan dengan bumbu rempah-rempah seperti serai, jahe, lengkuas, dan daun jeruk.',
                'cara' => 'Masak daging dalam santan dan bumbu rempah hingga empuk dan bumbu meresap.',
                'energi' => 380,
                'protein' => 30,
                'lemak' => 25,
                'karbo' => 10,
            ],
            [
                'nama' => 'Pisang Goreng',
                'bahan' => 'Pisang goreng adalah pisang yang digoreng dengan tepung terigu dan gula.',
                'cara' => 'Celupkan pisang dalam adonan tepung, goreng hingga kecoklatan.',
                'energi' => 160,
                'protein' => 2,
                'lemak' => 5,
                'karbo' => 30,
            ],
            [
                'nama' => 'Sayur Asem',
                'bahan' => 'Sayur asem adalah sayuran seperti kacang panjang, labu siam, jagung muda, dan terong rebus dalam kuah asam yang segar.',
                'cara' => 'Rebus sayuran dalam kuah asam dengan tambahan bumbu dan gula.',
                'energi' => 150,
                'protein' => 5,
                'lemak' => 3,
                'karbo' => 25,
            ],
            [
                'nama' => 'Sate Ayam',
                'bahan' => 'Sate ayam adalah potongan daging ayam yang ditusuk dan dibakar, disajikan dengan bumbu kacang atau kecap.',
                'cara' => 'Bakar sate hingga matang, sajikan dengan bumbu kacang atau kecap manis.',
                'energi' => 220,
                'protein' => 18,
                'lemak' => 10,
                'karbo' => 15,
            ],
            [
                'nama' => 'Ikan Bakar',
                'bahan' => 'Ikan bakar adalah ikan yang dibakar dengan bumbu rempah seperti bawang putih, bawang merah, kunyit, dan jeruk nipis.',
                'cara' => 'Bakar ikan hingga matang dan kecoklatan, sajikan dengan nasi dan sambal.',
                'energi' => 280,
                'protein' => 22,
                'lemak' => 14,
                'karbo' => 10,
            ],
            [
                'nama' => 'Es Teler',
                'bahan' => 'Es teler adalah es campur dengan potongan buah seperti alpukat, kelapa muda, nangka, dan cincau, disajikan dengan santan manis dan es serut.',
                'cara' => 'Campur potongan buah dengan es serut dan siram dengan santan manis.',
                'energi' => 180,
                'protein' => 3,
                'lemak' => 8,
                'karbo' => 40,
            ],
            [
                'nama' => 'Martabak Manis',
                'bahan' => 'Martabak manis adalah adonan tepung dengan isi cokelat, keju, kacang, dan gula, yang dibalut dan dipanggang hingga matang.',
                'cara' => 'Olesi wajan dengan minyak, tuang adonan martabak, tambahkan isi sesuai selera, lipat dan panggang hingga matang.',
                'energi' => 280,
                'protein' => 7,
                'lemak' => 15,
                'karbo' => 30,
            ],
            [
                'nama' => 'Sop Buntut',
                'bahan' => 'Sop buntut adalah sup dengan buntut sapi yang dimasak dalam kuah bening dengan bumbu rempah seperti merica, ketumbar, dan daun bawang.',
                'cara' => 'Rebus buntut sapi dengan bumbu rempah hingga empuk, sajikan dengan tambahan wortel, kentang, dan bawang goreng.',
                'energi' => 350,
                'protein' => 25,
                'lemak' => 20,
                'karbo' => 15,
            ],
            [
                'nama' => 'Bakmi Ayam',
                'bahan' => 'Bakmi ayam adalah mie rebus dengan potongan daging ayam, irisan bakso, dan sayuran, disajikan dengan kuah kaldu ayam.',
                'cara' => 'Rebus mie hingga matang, sajikan dengan daging ayam, bakso, dan kuah kaldu ayam.',
                'energi' => 320,
                'protein' => 15,
                'lemak' => 12,
                'karbo' => 40,
            ],
            [
                'nama' => 'Pempek',
                'bahan' => 'Pempek adalah makanan khas Palembang berbahan dasar tepung sagu dan ikan, disajikan dengan kuah cuko.',
                'cara' => 'Campur tepung sagu dan ikan, bentuk dan rebus hingga matang, sajikan dengan kuah cuko, irisan timun, dan tauge.',
                'energi' => 250,
                'protein' => 10,
                'lemak' => 15,
                'karbo' => 25,
            ],
            [
                'nama' => 'Sushi',
                'bahan' => 'Sushi adalah hidangan Jepang yang terdiri dari nasi yang dibentuk bersama bahan lain seperti ikan, telur, atau sayuran.',
                'cara' => 'Letakkan nasi di atas selembar nori, tambahkan irisan ikan atau sayuran, gulung dan potong.',
                'energi' => 210,
                'protein' => 8,
                'lemak' => 5,
                'karbo' => 35,
            ],
            [
                'nama' => 'Pancake',
                'bahan' => 'Pancake adalah adonan berbasis tepung terigu, telur, susu, dan gula, yang dipanggang dan disajikan dengan sirup maple.',
                'cara' => 'Tuang adonan pancake ke atas wajan panas, panggang hingga matang, sajikan dengan mentega dan sirup maple.',
                'energi' => 180,
                'protein' => 5,
                'lemak' => 6,
                'karbo' => 25,
            ],
            [
                'nama' => 'Bubur Sumsum',
                'bahan' => 'Bubur sumsum adalah bubur beras yang dimasak dengan santan dan gula, disajikan dengan tambahan bubur sumsum yang dibuat dari tepung beras.',
                'cara' => 'Rebus beras dengan santan dan gula hingga menjadi bubur, tambahkan tambahan bubur sumsum yang sudah direbus.',
                'energi' => 200,
                'protein' => 3,
                'lemak' => 8,
                'karbo' => 30,
            ],
            [
                'nama' => 'Nasi Uduk',
                'bahan' => 'Nasi uduk adalah nasi yang dimasak dengan santan dan daun pandan, disajikan dengan pelengkap seperti telur balado, tempe goreng, dan ayam goreng.',
                'cara' => 'Rebus nasi dengan santan dan daun pandan hingga matang, sajikan dengan pelengkap sesuai selera.',
                'energi' => 280,
                'protein' => 10,
                'lemak' => 15,
                'karbo' => 35,
            ],
            [
                'nama' => 'Es Campur',
                'bahan' => 'Es campur adalah campuran buah-buahan segar seperti alpukat, kelapa muda, cincau, dan agar-agar yang disajikan dengan sirup dan es serut.',
                'cara' => 'Campur semua bahan dalam mangkuk, siram dengan sirup dan es serut.',
                'energi' => 150,
                'protein' => 1,
                'lemak' => 5,
                'karbo' => 30,
            ],
            [
                'nama' => 'Pizza',
                'bahan' => 'Pizza adalah roti bundar dengan topping seperti saus tomat, keju, dan berbagai macam bahan tambahan seperti daging, sayuran, atau jamur.',
                'cara' => 'Olesi roti dengan saus tomat, tambahkan keju dan topping sesuai selera, panggang hingga keju meleleh.',
                'energi' => 320,
                'protein' => 12,
                'lemak' => 18,
                'karbo' => 30,
            ],
            [
                'nama' => 'Sate Padang',
                'bahan' => 'Sate Padang adalah potongan daging sapi yang dibumbui dengan bumbu rendang Padang dan dibakar, disajikan dengan kuah kacang kental.',
                'cara' => 'Marinasi daging dengan bumbu rendang Padang, tusuk dan bakar hingga matang, sajikan dengan kuah kacang.',
                'energi' => 250,
                'protein' => 20,
                'lemak' => 15,
                'karbo' => 10,
            ],
            [
                'nama' => 'Mie Ayam',
                'bahan' => 'Mie ayam adalah mie pangsit dengan potongan daging ayam dan pangsit rebus, disajikan dengan kuah kaldu ayam dan tambahan sayuran.',
                'cara' => 'Rebus mie dan pangsit hingga matang, sajikan dengan daging ayam, kaldu ayam, dan sayuran.',
                'energi' => 300,
                'protein' => 14,
                'lemak' => 10,
                'karbo' => 40,
            ],
            [
                'nama' => 'Pasta',
                'bahan' => 'Pasta adalah hidangan Italia berbahan dasar tepung terigu dan telur, disajikan dengan saus seperti bolognese atau carbonara.',
                'cara' => 'Rebus pasta hingga matang, campur dengan saus sesuai selera, sajikan dengan parmesan.',
                'energi' => 280,
                'protein' => 10,
                'lemak' => 12,
                'karbo' => 35,
            ],
            [
                'nama' => 'Bakwan Jagung',
                'bahan' => 'Bakwan jagung adalah gorengan berbahan dasar jagung, tepung terigu, dan bumbu-bumbu seperti bawang merah, daun bawang, dan garam.',
                'cara' => 'Campur semua bahan, aduk hingga rata, dan goreng dalam minyak panas hingga kecoklatan.',
                'energi' => 180,
                'protein' => 5,
                'lemak' => 8,
                'karbo' => 25,
            ],
            [
                'nama' => 'Bubur Ayam',
                'bahan' => 'Bubur ayam adalah bubur dengan nasi yang dimasak dalam kaldu ayam, disajikan dengan daging ayam suwir, telur rebus, dan bawang goreng.',
                'cara' => 'Rebus nasi dalam kaldu ayam hingga menjadi bubur, tambahkan daging ayam, telur rebus, dan bawang goreng.',
                'energi' => 240,
                'protein' => 12,
                'lemak' => 10,
                'karbo' => 30,
            ],
            [
                'nama' => 'Pasta Aglio e Olio',
                'bahan' => 'Pasta aglio e olio adalah hidangan pasta Italia dengan bawang putih cincang dan cabai merah dalam minyak zaitun.',
                'cara' => 'Tumis bawang putih dan cabai merah dalam minyak zaitun, tambahkan pasta yang telah direbus, aduk hingga tercampur rata.',
                'energi' => 290,
                'protein' => 8,
                'lemak' => 15,
                'karbo' => 35,
            ],
            [
                'nama' => 'Kue Lumpur',
                'bahan' => 'Kue lumpur adalah kue tradisional Indonesia yang terbuat dari tepung beras, santan, gula merah, dan parutan kelapa.',
                'cara' => 'Campur semua bahan, kukus atau panggang dalam cetakan hingga matang.',
                'energi' => 180,
                'protein' => 3,
                'lemak' => 8,
                'karbo' => 25,
            ],
            [
                'nama' => 'Es Puter',
                'bahan' => 'Es puter adalah es krim tradisional Indonesia yang terbuat dari santan, gula, dan bahan-bahan lain seperti pandan atau vanili.',
                'cara' => 'Campur semua bahan, aduk rata, tuang ke dalam cetakan es krim, dinginkan.',
                'energi' => 220,
                'protein' => 2,
                'lemak' => 12,
                'karbo' => 30,
            ],
            [
                'nama' => 'Ketoprak',
                'bahan' => 'Ketoprak adalah pecel dengan tambahan ketupat dan tahu, disiram dengan bumbu kacang kental.',
                'cara' => 'Campur tahu, ketupat, dan sayuran, siram dengan bumbu kacang.',
                'energi' => 260,
                'protein' => 10,
                'lemak' => 10,
                'karbo' => 35,
            ],
            [
                'nama' => 'Es Doger',
                'bahan' => 'Es doger adalah es krim berisi potongan nangka, kacang merah, dan ketan hitam, disiram dengan sirup gula merah.',
                'cara' => 'Campur semua bahan dalam mangkuk es, siram dengan sirup gula merah.',
                'energi' => 200,
                'protein' => 3,
                'lemak' => 8,
                'karbo' => 35,
            ],
            [
                'nama' => 'Soto Betawi',
                'bahan' => 'Soto Betawi adalah sup daging sapi dengan kuah santan yang kental, disajikan dengan irisan kentang dan tomat.',
                'cara' => 'Rebus daging sapi dengan bumbu hingga empuk, tambahkan santan dan irisan kentang, sajikan dengan tomat dan bawang goreng.',
                'energi' => 320,
                'protein' => 20,
                'lemak' => 18,
                'karbo' => 25,
            ],
            [
                'nama' => 'Bakpao',
                'bahan' => 'Bakpao adalah roti kukus berisi daging atau kacang, dengan adonan tepung terigu dan ragi.',
                'cara' => 'Isi adonan dengan daging atau kacang, kukus hingga matang.',
                'energi' => 180,
                'protein' => 5,
                'lemak' => 8,
                'karbo' => 25,
            ],
            [
                'nama' => 'Puding',
                'bahan' => 'Puding adalah hidangan penutup yang terbuat dari susu, gula, dan bahan lain seperti agar-agar atau tepung maizena.',
                'cara' => 'Rebus susu dengan gula dan bahan lain, dinginkan dalam cetakan.',
                'energi' => 150,
                'protein' => 3,
                'lemak' => 5,
                'karbo' => 20,
            ],
            [
                'nama' => 'Kwetiau Goreng',
                'bahan' => 'Kwetiau goreng adalah mie kwetiau yang digoreng dengan minyak sayur, tambahkan telur, daging ayam atau seafood, dan sayuran.',
                'cara' => 'Tumis bawang putih, tambahkan daging ayam atau seafood, telur, dan kwetiau, aduk hingga matang.',
                'energi' => 310,
                'protein' => 13,
                'lemak' => 16,
                'karbo' => 35,
            ],
            [
                'nama' => 'Es Cendol',
                'bahan' => 'Es cendol adalah minuman tradisional Indonesia dengan campuran tepung beras, santan, gula merah, dan es serut.',
                'cara' => 'Campur tepung beras dengan air, rebus hingga mengental, tambahkan santan dan gula merah, sajikan dengan es serut.',
                'energi' => 190,
                'protein' => 2,
                'lemak' => 6,
                'karbo' => 30,
            ],
            [
                'nama' => 'Sop Kambing',
                'bahan' => 'Sop kambing adalah sup dengan potongan daging kambing yang dimasak dalam kuah bening dengan bumbu rempah seperti merica, kayu manis, dan cengkeh.',
                'cara' => 'Rebus daging kambing dengan bumbu rempah hingga empuk, sajikan dengan tambahan kentang, wortel, dan bawang goreng.',
                'energi' => 340,
                'protein' => 30,
                'lemak' => 22,
                'karbo' => 10,
            ],
            [
                'nama' => 'Sambal Goreng Kentang',
                'bahan' => 'Sambal goreng kentang adalah kentang yang digoreng dan disajikan dengan sambal terasi dan potongan telur rebus.',
                'cara' => 'Goreng kentang hingga kecoklatan, sajikan dengan sambal terasi dan potongan telur rebus.',
                'energi' => 260,
                'protein' => 8,
                'lemak' => 15,
                'karbo' => 30,
            ],
            [
                'nama' => 'Martabak Telur',
                'bahan' => 'Martabak telur adalah adonan tepung terigu dengan isi telur, daging sapi cincang, dan bawang merah, yang dipanggang hingga matang.',
                'cara' => 'Olesi wajan dengan minyak, tuang adonan martabak, tambahkan isi telur, daging sapi cincang, dan bawang merah, lipat dan panggang hingga matang.',
                'energi' => 320,
                'protein' => 15,
                'lemak' => 18,
                'karbo' => 25,
            ],
            [
                'nama' => 'Cireng',
                'bahan' => 'Cireng adalah gorengan berbahan dasar tepung tapioka dengan tambahan bawang putih, daun bawang, dan garam.',
                'cara' => 'Campur semua bahan, aduk hingga rata, dan goreng dalam minyak panas hingga kecoklatan.',
                'energi' => 170,
                'protein' => 3,
                'lemak' => 8,
                'karbo' => 20,
            ],
        ];

        // Insert data into database using DB facade
        foreach ($foods as $food) {
            DB::table('menus')->insert([
                'nama' => $food['nama'],
                'bahan' => $food['bahan'],
                'cara' => $food['cara'],
                'energi' => $food['energi'],
                'protein' => $food['protein'],
                'lemak' => $food['lemak'],
                'karbo' => $food['karbo'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
